package com.marbleng.app.ui

// MARBLE_BILINGUAL_V111 — the Persian microcopy lexicon.
//
// MarbleStrings carries the strings that were designed bilingual from day one. The rest of the
// product surface (settings titles, subtitles, buttons, dialogs, badges) renders through the
// shared Prism components, and those components pass their visible copy through [trx] below.
// When Persian is active the exact English literal is looked up here; a miss falls back to the
// original English so a new string can never crash or blank a screen. Dynamic strings (counts,
// rates, times) are handled by the pattern rules at the bottom.

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable

/** Translate an arbitrary UI literal when Persian is the active product language. */
@Composable
@ReadOnlyComposable
internal fun trx(text: String): String {
    if (LocalMarbleStrings.current.language != MarbleLanguage.FA) return text
    return faTranslate(text)
}

/** Nullable convenience for optional titles/subtitles. */
@Composable
@ReadOnlyComposable
internal fun trxOrNull(text: String?): String? = text?.let { trx(it) }

internal fun faTranslate(text: String): String {
    if (text.isBlank()) return text
    FaLexicon[text]?.let { return it }
    val trimmed = text.trim()
    if (trimmed !== text) FaLexicon[trimmed]?.let { return text.replace(trimmed, it) }
    // Case-tolerant match: many call sites render UPPERCASE variants of lexicon keys.
    FaLexiconLower[trimmed.lowercase()]?.let { return it }
    faPattern(trimmed)?.let { return it }
    return text
}

private val FaLexicon: Map<String, String> = mapOf(
    // ------------------------------------------------------------------ navigation & common verbs
    "Home" to "خانه",
    "Servers" to "سرورها",
    "Settings" to "تنظیمات",
    "Routing" to "مسیریابی",
    "Privacy" to "حریم خصوصی",
    "Logs" to "گزارش‌ها",
    "System Doctor" to "پزشک سیستم",
    "History" to "تاریخچه",
    "Close" to "بستن",
    "Done" to "تمام",
    "Later" to "بعداً",
    "Save" to "ذخیره",
    "Cancel" to "لغو",
    "Delete" to "حذف",
    "Edit" to "ویرایش",
    "Add" to "افزودن",
    "Refresh" to "به‌روزرسانی",
    "Paste" to "چسباندن",
    "Import" to "وارد کردن",
    "Test" to "تست",
    "Details" to "جزئیات",
    "Rename" to "تغییر نام",
    "Dismiss message" to "بستن پیام",
    "View update" to "مشاهده به‌روزرسانی",
    "Selected" to "انتخاب‌شده",
    "Not selected" to "انتخاب‌نشده",
    "Prepare" to "آماده‌سازی",
    "Update" to "به‌روزرسانی",
    "Auto" to "خودکار",
    "Always" to "همیشه",
    "Off" to "خاموش",
    "On" to "روشن",
    "Custom" to "سفارشی",
    "Default" to "پیش‌فرض",
    "Device" to "دستگاه",
    "Local" to "محلی",
    "System" to "سیستم",

    // ------------------------------------------------------------------ MARBLE_SIGNATURE_HOME_V112
    "Home only" to "فقط خانه",
    "All pages" to "همه صفحه‌ها",
    "Glass" to "شیشه‌ای",
    "Colored" to "رنگی",
    "Plain" to "ساده",

    // ------------------------------------------------------------------ MARBLE_CONNECT_BUTTON_STYLES_V119
    "Connect button" to "دکمه اتصال",
    "One silhouette for every Home style" to "یک طرح واحد برای همه استایل‌های خانه",
    "Floating" to "شناور",
    "Core" to "هسته",
    "Pulse" to "ضربان",
    "Orbit" to "مداری",
    "Shield" to "سپر",
    "Subtle" to "ظریف",
    "Bold" to "پررنگ",
    "Hidden" to "محو",
    "Device default" to "پیش‌فرض دستگاه",
    "Electric" to "آبی الکتریک",
    "Emerald" to "زمردی",
    "Amethyst" to "بنفش",
    "Amber" to "کهربایی",
    "Ice" to "یخی",
    "Manual" to "دستی",
    "Signature" to "سیگنچر",
    "Pro studio" to "استودیو حرفه‌ای",
    "System font" to "فونت سیستم",
    "Add server" to "افزودن سرور",
    "Shortcut" to "میان‌بر",
    "Status banner" to "بنر وضعیت",
    "General" to "عمومی",
    "Tests" to "تست‌ها",
    "Engine" to "موتور",
    "Network" to "شبکه",
    "Smart" to "هوشمند",
    "Tunnel" to "تونل",
    "Workload" to "بار کاری",

    // ------------------------------------------------------------------ connection states
    "Protected" to "محافظت‌شده",
    "Securing route" to "در حال برقراری مسیر امن",
    "Fail-closed" to "قطع ایمن",
    "Ready to protect" to "آماده محافظت",
    "Connecting" to "در حال اتصال",
    "Connected" to "متصل",
    "Blocked" to "مسدود",
    "Connect" to "اتصال",
    "Disconnect" to "قطع اتصال",
    "Active" to "فعال",
    "Ready" to "آماده",
    "Missing" to "ناموجود",
    "Enabled" to "فعال",
    "Disabled" to "غیرفعال",
    "Waiting" to "در انتظار",
    "Fast" to "سریع",
    "Fair" to "متوسط",
    "Slow" to "کند",
    "Healthy" to "سالم",
    "Scanning" to "در حال پویش",
    "Scanning…" to "در حال پویش…",
    "Refreshing" to "در حال به‌روزرسانی",
    "Syncing" to "در حال همگام‌سازی",
    "Testing server" to "در حال تست سرور",
    "Server queued" to "سرور در صف تست",
    "Unknown host" to "میزبان ناشناخته",
    "Choose a route" to "یک مسیر انتخاب کنید",
    "Choose a server" to "یک سرور انتخاب کنید",
    "No server selected" to "هیچ سروری انتخاب نشده",
    "Connection issue" to "مشکل اتصال",
    "Heads up" to "توجه",
    "Completed" to "انجام شد",
    "Tap the orb to cancel" to "برای لغو، گوی را لمس کنید",
    "Tap the orb to disconnect" to "برای قطع اتصال، گوی را لمس کنید",
    "Tap the orb to retry" to "برای تلاش دوباره، گوی را لمس کنید",
    "Tap the orb to start" to "برای شروع، گوی را لمس کنید",
    "● PROTECTED" to "● محافظت‌شده",
    "● CONNECTING" to "● در حال اتصال",
    "● FAIL-CLOSED" to "● قطع ایمن",
    "○ READY" to "○ آماده",
    "LOCKED ON" to "قفل‌شده",
    "NO ROUTE" to "بدون مسیر",
    "KILL SWITCH" to "کلید اضطراری",
    "FULL TUN" to "تونل کامل",
    "Full TUN" to "تونل کامل",
    "Device-wide route" to "مسیر سراسری دستگاه",
    "DEVICE-WIDE" to "سراسری دستگاه",

    // ------------------------------------------------------------------ home metric labels
    "Ping" to "پینگ",
    "Jitter" to "لرزش",
    "Quality" to "کیفیت",
    "Live quality" to "کیفیت زنده",
    "Measured" to "اندازه‌گیری‌شده",
    "Reachable" to "در دسترس",
    "Throughput" to "توان عبوری",
    "Endpoint" to "نقطه پایانی",
    "not measured yet" to "هنوز اندازه‌گیری نشده",
    "Secure route details" to "جزئیات مسیر امن",
    "Inspect selected route" to "بازبینی مسیر انتخاب‌شده",
    "Waiting for verified HTTPS RTT" to "در انتظار تأخیر HTTPS تأییدشده",

    // ------------------------------------------------------------------ IP details dialog
    "IP details" to "جزئیات آی‌پی",
    "Public route information for the connected server" to "اطلاعات مسیر عمومی سرور متصل",
    "Resolving the public IP…" to "در حال دریافت آی‌پی عمومی…",
    "Destination" to "مقصد",
    "Type" to "نوع",
    "Location" to "موقعیت",
    "Country" to "کشور",
    "Domain" to "دامنه",
    "Hosting" to "میزبانی",
    "Proxy" to "پروکسی",
    "Tor" to "تور",
    "Signals" to "نشانه‌ها",
    "No flags" to "بدون نشانه",
    "Only the resolved public endpoint is queried; credentials and subscription data stay local." to
        "فقط نقطه پایانی عمومی استعلام می‌شود؛ اطلاعات ورود و داده اشتراک‌ها محلی می‌مانند.",
    "Server IP" to "آی‌پی سرور",
    "Family" to "خانواده",
    "City" to "شهر",
    "Datacenter / network" to "مرکز داده / شبکه",
    "HOSTING / DC" to "میزبانی / مرکز داده",
    "PUBLIC NETWORK" to "شبکه عمومی",
    "Visit provider website" to "مشاهده وب‌سایت ارائه‌دهنده",
    "Resolving the selected server and loading public network metadata…" to
        "در حال یافتن سرور انتخاب‌شده و بارگیری اطلاعات شبکه عمومی…",
    "Server metadata has not been loaded yet." to "اطلاعات سرور هنوز بارگیری نشده است.",
    "Server info" to "اطلاعات سرور",
    "Selected route" to "مسیر انتخاب‌شده",
    "ENDPOINT" to "نقطه پایانی",

    // ------------------------------------------------------------------ update dialog
    "A fresh MarbleNG build is ready" to "نسخه تازه MarbleNG آماده است",
    "A newer signed release is available on GitHub." to "نسخه امضاشده جدیدتری در گیت‌هاب موجود است.",
    "WHAT CHANGED" to "تغییرات",
    "Swipe up to read all changes" to "برای خواندن همه تغییرات به بالا بکشید",
    "All changes shown" to "همه تغییرات نمایش داده شد",
    "Could not open the MarbleNG Releases page" to "صفحه انتشارهای MarbleNG باز نشد",
    "No data yet" to "هنوز داده‌ای نیست",

    // ------------------------------------------------------------------ library
    "Search servers, host or protocol" to "جستجوی سرور، میزبان یا پروتکل",
    "Search servers" to "جستجوی سرورها",
    "Subscription" to "اشتراک",
    "Manual config" to "پیکربندی دستی",
    "Manual server" to "سرور دستی",
    "Chain proxy" to "پروکسی زنجیره‌ای",
    "All" to "همه",
    "Reverse" to "معکوس",
    "Rank" to "رتبه‌بندی",
    "Score" to "امتیاز",
    "Name" to "نام",
    "Protocol" to "پروتکل",
    "Source" to "منبع",
    "Sources" to "منابع",
    "Sort" to "مرتب‌سازی",
    "SORT:" to "مرتب‌سازی:",
    "No connections yet" to "هنوز اتصالی وجود ندارد",
    "Nothing matches" to "چیزی مطابقت ندارد",
    "Nothing here yet." to "هنوز چیزی اینجا نیست.",
    "Filter & sort" to "فیلتر و مرتب‌سازی",
    "Focus Servers without changing any server" to "تمرکز روی سرورها بدون تغییر هیچ سروری",
    "Select one subscription or show everything" to "یک اشتراک را انتخاب کنید یا همه را ببینید",
    "Fastest, strongest or easiest to find" to "سریع‌ترین، قوی‌ترین یا آسان‌ترین برای یافتن",
    "VIEW SERVERS" to "مشاهده سرورها",
    "Remove failed" to "حذف ناموفق‌ها",
    "Delete source" to "حذف منبع",
    "Copy URL" to "کپی لینک",
    "Subscription URL copied" to "لینک اشتراک کپی شد",
    "Copy servers" to "کپی سرورها",
    "Clean failed tests" to "پاک‌سازی تست‌های ناموفق",
    "Only servers with a stored failed result of that exact test type are removed." to
        "فقط سرورهایی حذف می‌شوند که نتیجه ناموفق ذخیره‌شده از همان نوع تست دارند.",
    "Local source" to "منبع محلی",
    "Create local source" to "ساخت منبع محلی",
    "Add subscription" to "افزودن اشتراک",
    "Subscription URL • optional" to "لینک اشتراک • اختیاری",
    "Name • optional" to "نام • اختیاری",
    "Display name" to "نام نمایشی",
    "Manage subscription" to "مدیریت اشتراک",
    "Source name" to "نام منبع",
    "Subscription URL" to "لینک اشتراک",
    "Edit server" to "ویرایش سرور",
    "Edit Xray JSON" to "ویرایش JSON اکس‌ری",
    "Effective config JSON" to "JSON پیکربندی نهایی",
    "Manual server • edits are stored locally." to "سرور دستی • ویرایش‌ها به‌صورت محلی ذخیره می‌شوند.",
    "Save JSON" to "ذخیره JSON",
    "Delete server?" to "این سرور حذف شود؟",
    "Swipe never deletes silently." to "کشیدن هرگز بی‌صدا حذف نمی‌کند.",
    "Copy config link" to "کپی لینک پیکربندی",
    "Copy Xray JSON" to "کپی JSON اکس‌ری",
    "Duplicate to Manual" to "کپی به منبع دستی",
    "Test this server" to "تست این سرور",
    "Copy config" to "کپی پیکربندی",
    "Config copied" to "پیکربندی کپی شد",
    "Copy JSON" to "کپی JSON",
    "Xray JSON copied" to "JSON اکس‌ری کپی شد",
    "Local Freedom engine" to "موتور آزادی محلی",
    "Back to servers" to "بازگشت به سرورها",
    "Chain name • optional" to "نام زنجیره • اختیاری",
    "Choose at least two servers below." to "دست‌کم دو سرور را در پایین انتخاب کنید.",
    "Move hop up" to "جابه‌جایی گام به بالا",
    "Move hop down" to "جابه‌جایی گام به پایین",
    "Remove hop" to "حذف گام",
    "Showing 24 servers • search to find any other server" to
        "نمایش ۲۴ سرور • برای یافتن سرورهای دیگر جستجو کنید",
    "Select one server source first, or enable Manual source." to
        "ابتدا یک منبع سرور انتخاب کنید یا منبع دستی را فعال کنید.",
    "Select one server source first" to "ابتدا یک منبع سرور انتخاب کنید",
    "Will be added to the selected source and kept across refreshes." to
        "به منبع انتخاب‌شده افزوده می‌شود و با به‌روزرسانی‌ها حفظ خواهد شد.",
    "All sources is only a view. Select a source chip first, then add the config." to
        "«همه» فقط یک نماست. ابتدا یک منبع را انتخاب کنید، سپس پیکربندی را بیفزایید.",
    "Save SSH connection" to "ذخیره اتصال SSH",
    "Save manual config" to "ذخیره پیکربندی دستی",
    "Xray config / outbound JSON" to "پیکربندی اکس‌ری / JSON خروجی",

    // ------------------------------------------------------------------ manual editor fields
    "Host" to "میزبان",
    "HOST" to "میزبان",
    "Port" to "پورت",
    "PORT" to "پورت",
    "Password" to "گذرواژه",
    "Username" to "نام کاربری",
    "Method" to "روش",
    "Auth" to "احراز هویت",
    "Cipher" to "رمزنگاری",
    "Flow" to "جریان",
    "VLESS encryption" to "رمزنگاری VLESS",
    "Fingerprint" to "اثر انگشت",
    "Cipher Suites (: separated)" to "مجموعه رمزها (جداشده با :)",
    "Allow insecure TLS" to "اجازه TLS ناامن",
    "TLS server name" to "نام سرور TLS",
    "Host key SHA256 • optional" to "SHA256 کلید میزبان • اختیاری",
    "TCP via protected loopback; UDP blocked." to "TCP از حلقه محافظت‌شده؛ UDP مسدود است.",
    "Private key" to "کلید خصوصی",
    "Local address / CIDR" to "نشانی محلی / CIDR",
    "Peer public key" to "کلید عمومی همتا",
    "Pre-shared key" to "کلید از پیش تقسیم‌شده",
    "Allowed IPs" to "آی‌پی‌های مجاز",
    "Reserved" to "رزروشده",
    "Keepalive" to "نگه‌داشتن اتصال",
    "Userspace WireGuard" to "وایرگارد فضای کاربر",
    "Transport" to "انتقال",
    "Path" to "مسیر",
    "Host header" to "سربرگ میزبان",
    "Service name" to "نام سرویس",
    "Authority" to "مرجع",
    "Security" to "امنیت",
    "REALITY public key" to "کلید عمومی REALITY",
    "Short ID" to "شناسه کوتاه",
    "Spider X" to "اسپایدر X",
    "Save to" to "ذخیره در",
    "`unsafe` uses native Go TLS; empty Cipher Suites = automatic." to
        "گزینه unsafe از TLS بومی Go استفاده می‌کند؛ مجموعه رمز خالی یعنی خودکار.",

    // ------------------------------------------------------------------ settings hub
    "Expert workspace" to "میز کار حرفه‌ای",
    "Show advanced options" to "نمایش گزینه‌های پیشرفته",
    "Appearance" to "ظاهر",
    "Theme, typeface & per-app proxy" to "پوسته، قلم و پروکسی هر برنامه",
    "Connection" to "اتصال",
    "Tunnel, proxy, port" to "تونل، پروکسی، پورت",
    "Subscriptions" to "اشتراک‌ها",
    "Refresh & sources" to "به‌روزرسانی و منابع",
    "Freedom Engine" to "موتور آزادی",
    "Serverless DPI bypass" to "عبور از DPI بدون سرور",
    "Testing" to "تست",
    "Tunnel, ICMP and live route" to "تونل، ICMP و مسیر زنده",
    "Intelligence" to "هوشمندی",
    "Adaptive routing" to "مسیریابی تطبیقی",
    "Split tunneling" to "تونل انتخابی",
    "App tunnel / bypass" to "تونل / دورزدن برای برنامه‌ها",
    "Geo assets & rules" to "داده‌ها و قواعد جغرافیایی",
    "Iran Mode" to "حالت ایران",
    "Filter detection" to "تشخیص فیلترینگ",
    "TUN & DoH" to "TUN و DoH",
    "Fragment & Mux" to "فرگمنت و ماکس",
    "DPI resilience" to "مقاومت در برابر DPI",
    "Notifications" to "اعلان‌ها",
    "Alerts" to "هشدارها",
    "Bug Finder" to "اشکال‌یاب",
    "Diagnostics" to "عیب‌یابی",
    "Expert controls" to "کنترل‌های حرفه‌ای",
    "Show every option here." to "نمایش همه گزینه‌ها در اینجا.",
    "Expert controls enabled" to "کنترل‌های حرفه‌ای فعال شد",
    "Advanced workspaces are visible" to "میزهای کار پیشرفته نمایان شدند",
    "If you're an expert, tap here" to "اگر حرفه‌ای هستید، اینجا بزنید",
    "Reveal advanced routing, engine and diagnostic controls" to
        "نمایش کنترل‌های پیشرفته مسیریابی، موتور و عیب‌یابی",

    // appearance
    "Theme" to "پوسته",
    "Follow device" to "مطابق دستگاه",
    "Light" to "روشن",
    "Prism light" to "روشن منشوری",
    "AMOLED" to "آمولد",
    "Pure black" to "مشکی خالص",
    "Typeface" to "قلم",
    "Persian" to "فارسی",
    "Product sans" to "قلم استاندارد",
    "Serif" to "سریف",
    "Per-app proxy" to "پروکسی هر برنامه",
    "Choose which installed apps use the tunnel" to
        "انتخاب کنید کدام برنامه‌ها از تونل استفاده کنند",
    "App list" to "فهرست برنامه‌ها",
    "Add or remove apps on the tunnel" to "افزودن یا حذف برنامه‌ها از تونل",
    "Installed apps" to "برنامه‌های نصب‌شده",
    "Tunnel or bypass per app" to "تونل یا دورزدن برای هر برنامه",
    "Add to Servers" to "افزودن به سرورها",
    "Subscription or manual config" to "اشتراک یا پیکربندی دستی",
    "Refresh all subscriptions" to "به‌روزرسانی همه اشتراک‌ها",
    "Rank all servers" to "رتبه‌بندی همه سرورها",
    "Unlimited" to "نامحدود",
    "Expired" to "منقضی‌شده",
    "All apps" to "همه برنامه‌ها",
    "Only selected" to "فقط انتخاب‌شده‌ها",
    "Bypass" to "دورزدن",
    "Bypass selected" to "دورزدن انتخاب‌شده‌ها",
    "Proxy list" to "فهرست پروکسی",
    "Exclude list" to "فهرست مستثنی",
    "App update checks" to "بررسی به‌روزرسانی برنامه",
    "Look for signed MarbleNG releases" to "جستجوی نسخه‌های امضاشده MarbleNG",
    "Search installed apps" to "جستجوی برنامه‌های نصب‌شده",
    "Loading installed apps…" to "در حال بارگیری برنامه‌های نصب‌شده…",
    "Applies on next Full TUN connect." to "در اتصال بعدی تونل کامل اعمال می‌شود.",

    // connection
    "Local SOCKS port" to "پورت SOCKS محلی",

    // intelligence
    "Marble Intelligence Engine" to "موتور هوشمند ماربل",
    "Adaptive per-network policies" to "سیاست‌های تطبیقی برای هر شبکه",
    "Maximum config compatibility" to "بیشترین سازگاری پیکربندی",
    "Verify the final config with Xray" to "بررسی پیکربندی نهایی با اکس‌ری",
    "Verified performance auto-tune" to "تنظیم خودکار کارایی تأییدشده",
    "Keep only proven gains" to "فقط بهبودهای اثبات‌شده حفظ شوند",
    "Marble Turbo acceleration" to "شتاب‌دهی توربوی ماربل",
    "Pick the fastest transport on connect" to "انتخاب سریع‌ترین انتقال هنگام اتصال",
    "Connect tuning budget" to "بودجه تنظیم هنگام اتصال",
    "Strategies per pass" to "راهبردها در هر دور",
    "Keep improving while connected" to "بهبود مستمر در حین اتصال",
    "Learn in background, keep the tunnel" to "یادگیری در پس‌زمینه با حفظ تونل",
    "Live tuning interval" to "بازه تنظیم زنده",
    "Ping that triggers tuning" to "پینگ آغازگر تنظیم",
    "Minimum gain to learn" to "کمینه بهبود برای یادگیری",
    "Adaptive tunnel datapath" to "مسیر داده تطبیقی تونل",
    "Size buffers from real throughput" to "اندازه بافر بر پایه توان عبوری واقعی",
    "Learn faster route now" to "یافتن مسیر سریع‌تر همین حالا",
    "Continuous Marble Autopilot" to "خلبان خودکار پیوسته ماربل",
    "Verify route, rotate challenges" to "بررسی مسیر و چرخش چالش‌ها",
    "Autopilot interval" to "بازه خلبان خودکار",
    "Challengers per cycle" to "رقیب‌ها در هر چرخه",
    "Deep speed cycle" to "چرخه سرعت عمیق",
    "Switch cooldown" to "فاصله بین تعویض‌ها",
    "Evidence confirmations" to "تأییدهای شواهد",
    "Protect heavy downloads" to "محافظت از دانلودهای سنگین",
    "Pause scans during downloads" to "توقف پویش هنگام دانلود",
    "Persistent route intelligence" to "هوش مسیر ماندگار",
    "Health history per network" to "تاریخچه سلامت برای هر شبکه",
    "Connection race" to "مسابقه اتصال",
    "First healthy route wins" to "اولین مسیر سالم برنده است",
    "Race width" to "پهنای مسابقه",
    "Smart fallback" to "جایگزین هوشمند",
    "Fail-closed switch to a backup" to "تعویض ایمن به مسیر پشتیبان",
    "Fallback depth" to "عمق جایگزینی",
    "Auto-connect after kill switch" to "اتصال خودکار پس از کلید اضطراری",
    "Off = tap Connect again" to "خاموش = دوباره اتصال را بزنید",
    "Network-change recovery" to "بازیابی هنگام تغییر شبکه",
    "Re-probe after Wi-Fi ↔ cellular" to "پویش دوباره پس از جابه‌جایی وای‌فای و دیتا",
    "Adaptive MTU" to "MTU تطبیقی",
    "Match the real link MTU" to "تطبیق با MTU واقعی پیوند",
    "MTU floor" to "کف MTU",
    "MTU ceiling" to "سقف MTU",
    "Thermal-aware benchmarking" to "تست آگاه از دما",
    "Ease off before throttling" to "کاهش فشار پیش از داغ‌شدن",
    "Adaptive throughput test" to "تست توان عبوری تطبیقی",
    "Start small, grow on trust" to "شروع کوچک، رشد با اعتماد",
    "UDP / QUIC probe" to "پویش UDP / QUIC",
    "Real UDP health via STUN" to "سلامت واقعی UDP با STUN",
    "Privacy sentinel" to "نگهبان حریم خصوصی",

    // notifications
    "Grant notification access" to "دادن دسترسی اعلان",
    "Test alert" to "هشدار آزمایشی",
    "Channels" to "کانال‌ها",
    "Clear optional alerts" to "پاک‌کردن هشدارهای اختیاری",
    "Live connection telemetry" to "تله‌متری زنده اتصال",
    "Ping and rates in the status" to "پینگ و سرعت در نوار وضعیت",
    "Optional smart alerts" to "هشدارهای هوشمند اختیاری",
    "Master switch for event alerts" to "کلید اصلی هشدار رویدادها",
    "Connection events" to "رویدادهای اتصال",
    "Route changes" to "تغییرات مسیر",
    "Recovery & failover" to "بازیابی و جایگزینی",
    "Fallback and recovery" to "جایگزینی و بازیابی",
    "Privacy warnings" to "هشدارهای حریم خصوصی",
    "Kill switch, blocked routes" to "کلید اضطراری و مسیرهای مسدود",
    "Network changes" to "تغییرات شبکه",
    "Wi-Fi ↔ cellular switches" to "جابه‌جایی وای‌فای و دیتا",
    "Subscription updates" to "به‌روزرسانی اشتراک‌ها",
    "Refresh results, failures" to "نتایج به‌روزرسانی و خطاها",
    "Core updates" to "به‌روزرسانی هسته",
    "Newer Xray or HEV core" to "هسته جدیدتر Xray یا HEV",
    "Alert cooldown (seconds)" to "فاصله هشدارها (ثانیه)",
    "SMART ALERTS ON" to "هشدار هوشمند روشن",
    "SMART ALERTS OFF" to "هشدار هوشمند خاموش",
    "LIVE STATUS" to "وضعیت زنده",
    "STATIC STATUS" to "وضعیت ایستا",
    "PERMISSION READY" to "دسترسی آماده",
    "PERMISSION NEEDED" to "نیازمند دسترسی",

    // fragment & mux
    "Adaptive Fragment" to "فرگمنت تطبیقی",
    "Try Fragment only after interference" to "فرگمنت فقط پس از اختلال",
    "Adaptive Mux" to "ماکس تطبیقی",
    "Try Mux only on stable routes" to "ماکس فقط روی مسیرهای پایدار",
    "TLS ClientHello fragmentation" to "قطعه‌قطعه‌سازی TLS ClientHello",
    "Split the first packet on dial" to "تقسیم اولین بسته هنگام شماره‌گیری",
    "Packets" to "بسته‌ها",
    "Length" to "طول",
    "Interval" to "بازه",
    "Mux / XUDP" to "ماکس / XUDP",
    "Reuse connections for small streams" to "استفاده دوباره از اتصال‌ها برای جریان‌های کوچک",
    "TCP concurrency" to "هم‌زمانی TCP",
    "XUDP concurrency" to "هم‌زمانی XUDP",

    // IPv6 / DNS
    "IPv6" to "IPv6",
    "Enable IPv6" to "فعال‌سازی IPv6",
    "IPv6 in the tunnel; off blocks ::/0" to "IPv6 در تونل؛ خاموش یعنی مسدودسازی ::/0",
    "Prefer IPv6" to "اولویت IPv6",
    "IPv6 first; auto-paused on IPv4 nets" to "اول IPv6؛ در شبکه‌های IPv4 خودکار متوقف می‌شود",
    "Blocked fail-closed" to "مسدود با قطع ایمن",
    "Preferred on this network" to "ترجیح‌داده‌شده در این شبکه",
    "Ready • no v6 route here" to "آماده • این‌جا مسیر v6 نیست",
    "ACTIVE FAMILY POLICY" to "سیاست فعال خانواده آی‌پی",
    "::/0 blocked" to "‏::/0 مسدود",
    "::/0 through the tunnel" to "‏::/0 از تونل",
    "IPv6 ENABLED" to "IPv6 فعال",
    "IPv6 BLOCKED" to "IPv6 مسدود",
    "IPv6 PREFERRED" to "IPv6 مقدم",
    "IPv6 PREFERENCE WAITING" to "اولویت IPv6 در انتظار",
    "IPv4 / AUTO" to "IPv4 / خودکار",
    "Intercept traditional DNS" to "رهگیری DNS سنتی",
    "Port 53 → encrypted DNS" to "پورت ۵۳ ← DNS رمزنگاری‌شده",
    "Adaptive DoH ordering" to "چینش تطبیقی DoH",
    "Keep the fastest DoH path" to "حفظ سریع‌ترین مسیر DoH",
    "Adaptive IPv4 / IPv6 DNS" to "‏DNS تطبیقی IPv4 / IPv6",
    "DNS family follows the link" to "خانواده DNS تابع پیوند است",
    "Resolvers" to "حل‌کننده‌ها",
    "Primary DoH" to "DoH اصلی",
    "Secondary DoH" to "DoH دوم",
    "TUN DNS 1" to "‏DNS تونل ۱",
    "TUN DNS 2" to "‏DNS تونل ۲",
    "A + AAAA" to "A + AAAA",
    "IPv4 ONLY" to "فقط IPv4",
    "IPv6 ONLY" to "فقط IPv6",
    "DNS HIJACK" to "رهگیری DNS",
    "DNS OPEN" to "‏DNS باز",
    "NO KILL SWITCH" to "بدون کلید اضطراری",

    // routing
    "Recommended Iran policy" to "سیاست پیشنهادی ایران",
    "Iran direct" to "ایران مستقیم",
    "Iran proxied" to "ایران از پروکسی",
    "Ads blocked" to "تبلیغات مسدود",
    "Ads allowed" to "تبلیغات مجاز",
    "Restore recommended policy" to "بازگردانی سیاست پیشنهادی",
    "Bypass Iranian traffic" to "دورزدن ترافیک ایران",
    ".ir direct, rest proxied" to "‏.ir مستقیم، بقیه از پروکسی",
    "Aggressive ad blocking" to "مسدودسازی تهاجمی تبلیغات",
    "Block ads before other rules" to "مسدودسازی تبلیغات پیش از قواعد دیگر",
    "Routing mode" to "حالت مسیریابی",
    "Proxy all" to "همه از پروکسی",
    "Private direct" to "خصوصی مستقیم",
    "Geo direct" to "جغرافیایی مستقیم",
    "Geo data" to "داده جغرافیایی",
    "geoip.dat source" to "منبع geoip.dat",
    "geosite.dat source" to "منبع geosite.dat",
    "Verify with Xray" to "بررسی با اکس‌ری",
    "Geo direct rules" to "قواعد مستقیم جغرافیایی",
    "GeoIP direct tags" to "برچسب‌های مستقیم GeoIP",
    "GeoSite direct tags" to "برچسب‌های مستقیم GeoSite",
    "Bypass private networks" to "دورزدن شبکه‌های خصوصی",
    "LAN stays direct" to "شبکه محلی مستقیم می‌ماند",
    "Domain strategy" to "راهبرد دامنه",
    "Ad geosite category" to "دسته تبلیغات geosite",
    "Exceptions & advanced rules" to "استثناها و قواعد پیشرفته",
    "Always proxy domains / geosite tags" to "دامنه‌ها / برچسب‌های همیشه از پروکسی",
    "Block domains / geosite tags" to "دامنه‌ها / برچسب‌های مسدود",
    "Block IP / CIDR / geoip tags" to "آی‌پی / CIDR / برچسب‌های مسدود",
    "Custom direct domains / geosite tags" to "دامنه‌ها / برچسب‌های مستقیم سفارشی",
    "Custom direct IP / CIDR / geoip tags" to "آی‌پی / CIDR / برچسب‌های مستقیم سفارشی",

    // subscriptions settings
    "Manual source" to "منبع دستی",
    "Show the built-in Manual source" to "نمایش منبع دستی داخلی",
    "Automatic refresh" to "به‌روزرسانی خودکار",
    "Refresh stale sources on start" to "به‌روزرسانی منابع قدیمی هنگام شروع",
    "Refresh cadence" to "آهنگ به‌روزرسانی",
    "Refresh all now" to "به‌روزرسانی همه، همین حالا",

    // bug finder / diagnostics
    "Runtime observatory" to "رصدخانه اجرا",
    "Debug TXT log" to "گزارش متنی اشکال‌زدایی",
    "Off by default" to "به‌صورت پیش‌فرض خاموش",
    "Report location" to "محل گزارش",
    "Run scan" to "اجرای پویش",
    "Copy report" to "کپی گزارش",
    "Bug Finder report copied" to "گزارش اشکال‌یاب کپی شد",
    "Save TXT snapshot" to "ذخیره تصویر متنی",
    "Hide checks" to "پنهان‌کردن بررسی‌ها",
    "Safe runtime reset" to "بازنشانی ایمن اجرا",
    "DEBUG ON" to "اشکال‌زدایی روشن",

    // probes / testing
    "Real tunnel" to "تونل واقعی",
    "TCP ping" to "پینگ TCP",
    "ICMP ping" to "پینگ ICMP",
    "TCP gate, then real test" to "دروازه TCP، سپس تست واقعی",
    "Most accurate" to "دقیق‌ترین",
    "Fastest" to "سریع‌ترین",
    "Classic ping" to "پینگ کلاسیک",
    "Samples per server" to "نمونه برای هر سرور",
    "Timeout per try" to "مهلت هر تلاش",
    "Servers per test run" to "سرور در هر دور تست",
    "Also measure download speed" to "اندازه‌گیری سرعت دانلود هم",
    "Slower, uses data" to "کندتر، مصرف داده دارد",
    "Grow the speed sample" to "رشد نمونه سرعت",
    "More only from fast servers" to "بیشتر فقط از سرورهای سریع",
    "ICMP bypasses the proxy; only Real tunnel proves the route." to
        "‏ICMP از پروکسی عبور نمی‌کند؛ فقط تونل واقعی مسیر را ثابت می‌کند.",

    // iran mode
    "Detect ISP" to "تشخیص اپراتور",
    "Force on" to "همیشه روشن",
    "Disable" to "غیرفعال",
    "Apply countermeasures" to "اعمال اقدام‌های مقابله‌ای",
    "Fragment, DNS order, MTU, failover" to "فرگمنت، ترتیب DNS، MTU، جایگزینی",
    "Domestic traffic direct" to "ترافیک داخلی مستقیم",
    "Keep .ir sites off the tunnel" to "سایت‌های .ir خارج از تونل",
    "Fingerprint the filtering" to "انگشت‌نگاری از فیلترینگ",
    "DNS injection, SNI resets, UDP" to "تزریق DNS، ریست SNI، UDP",
    "ENGINE ON" to "موتور روشن",
    "ENGINE IDLE" to "موتور بیکار",
    "Re-scan now" to "پویش دوباره",
    "Ready to switch on" to "آماده روشن‌شدن",
    "IRAN MODE • FORCED ON" to "حالت ایران • همیشه روشن",
    "IRAN MODE • SCANNING" to "حالت ایران • در حال پویش",
    "IRAN MODE • ACTIVE" to "حالت ایران • فعال",

    // freedom engine
    "Marble Freedom" to "ماربل فریدم",
    "TCP FALLBACK" to "جایگزین TCP",
    "QUIC PADDING" to "لایه‌گذاری QUIC",
    "IR DIRECT" to "ایران مستقیم",
    "YouTube / media TCP fallback" to "جایگزین TCP برای یوتیوب / رسانه",
    "Block QUIC so video uses the chain" to "مسدودسازی QUIC تا ویدیو از زنجیره برود",
    "Evasion preset" to "پیش‌تنظیم گریز",
    "Start balanced; escalate on harsh filters." to "شروع متعادل؛ تشدید در فیلترینگ سخت.",
    "Smart Auto" to "خودکار هوشمند",
    "Best everyday default" to "بهترین پیش‌فرض روزمره",
    "Stable 2-hop" to "دوگامه پایدار",
    "Social and video" to "شبکه اجتماعی و ویدیو",
    "SNI split" to "شکستن SNI",
    "Light split" to "شکستن سبک",
    "Slow-first" to "اول آهسته",
    "Strict reset filters" to "فیلترهای ریست سخت‌گیر",
    "Extreme" to "بیشینه",
    "Strongest 2-hop" to "قوی‌ترین دوگامه",
    "Manual tuning" to "تنظیم دستی",
    "Operator profile" to "نمایه اپراتور",
    "Per-carrier chains; Auto picks by ASN." to "زنجیره برای هر اپراتور؛ خودکار با ASN انتخاب می‌کند.",
    "Auto-apply detected operator" to "اعمال خودکار اپراتور تشخیص‌داده‌شده",
    "Match MCI / Irancell / Rightel / Shatel" to "تطبیق با همراه اول / ایرانسل / رایتل / شاتل",
    "Shatel" to "شاتل",
    "Fixed-line chain" to "زنجیره خط ثابت",
    "MCI • همراه اول" to "همراه اول",
    "Strictest DPI" to "سخت‌گیرترین DPI",
    "Irancell" to "ایرانسل",
    "Throttle-heavy" to "با محدودسازی شدید",
    "Rightel" to "رایتل",
    "Mobile chain" to "زنجیره موبایل",
    "Fragment chain" to "زنجیره فرگمنت",
    "Two hops stay fast; add the middle only if needed." to "دو گام سریع می‌ماند؛ گام میانی فقط در صورت نیاز.",
    "Outer hop" to "گام بیرونی",
    "First-write split • hides SNI" to "شکستن اولین نوشتن • پنهان‌سازی SNI",
    "Middle hop" to "گام میانی",
    "Optional • off by default" to "اختیاری • به‌صورت پیش‌فرض خاموش",
    "Inner hop" to "گام درونی",
    "Byte-level split on dial" to "شکستن بایت‌به‌بایت هنگام اتصال",
    "Encrypted DNS" to "‏DNS رمزنگاری‌شده",
    "Pinned DoH; classic DNS stays in the tunnel." to "‏DoH سنجاق‌شده؛ DNS کلاسیک در تونل می‌ماند.",
    "Smart multi-resolver cascade" to "آبشار چندحل‌کننده هوشمند",
    "Race DoH endpoints" to "مسابقه نقاط DoH",
    "Hijack classic DNS (port 53)" to "رهگیری DNS کلاسیک (پورت ۵۳)",
    "Domestic (.ir) & private direct" to "داخلی (.ir) و خصوصی مستقیم",
    ".ir and LAN off the chain" to "‏.ir و شبکه محلی خارج از زنجیره",
    "DoH endpoints" to "نقاط پایانی DoH",
    "Fallback DoH" to "DoH جایگزین",
    "Clean DoH pool (comma-separated)" to "استخر DoH تمیز (جداشده با کاما)",
    "Bootstrap IPs" to "آی‌پی‌های راه‌انداز",
    "Primary IP" to "آی‌پی اصلی",
    "Secondary IP" to "آی‌پی دوم",
    "Record strategy" to "راهبرد رکورد",
    "IPv4" to "IPv4",
    "Domain routing" to "مسیریابی دامنه",
    "QUIC / UDP policy" to "سیاست QUIC / UDP",
    "TCP fallback is on; QUIC padding waits." to "جایگزین TCP روشن است؛ لایه‌گذاری QUIC منتظر می‌ماند.",
    "Pad UDP/443 only where UDP is allowed." to "لایه‌گذاری UDP/443 فقط جایی که UDP مجاز است.",
    "Dedicated QUIC padding" to "لایه‌گذاری اختصاصی QUIC",
    "Pads UDP/443; off while TCP fallback is on" to "لایه‌گذاری UDP/443؛ با جایگزین TCP خاموش است",
    "Noise burst pairs" to "جفت‌های نویز انفجاری",
    "IPv4 size (B)" to "اندازه IPv4 (بایت)",
    "IPv4 delay (ms)" to "تأخیر IPv4 (میلی‌ثانیه)",
    "IPv6 size (B)" to "اندازه IPv6 (بایت)",
    "IPv6 delay (ms)" to "تأخیر IPv6 (میلی‌ثانیه)",
    "Restore Freedom defaults" to "بازگردانی پیش‌فرض‌های فریدم",
    "Marble Freedom settings restored to defaults" to "تنظیمات ماربل فریدم به پیش‌فرض بازگشت",
    "FREEDOM  •  fragment" to "فریدم  •  فرگمنت",

    // home quick settings / misc
    "Link-aware" to "آگاه از پیوند",
    "Auto recovery" to "بازیابی خودکار",
    "Kill-switch reconnect" to "اتصال دوباره پس از کلید اضطراری",
    "Networks" to "شبکه‌ها",
    "Uptime" to "مدت اتصال",

    // ------------------------------------------------------------------ permission onboarding
    "Allow VPN access" to "اجازه دسترسی VPN",
    "MarbleNG needs Android's VPN permission to arm its protected connection service. It only routes traffic through the server you choose; it cannot read your messages or files." to
        "MarbleNG برای فعال‌سازی سرویس اتصال محافظت‌شده به مجوز VPN اندروید نیاز دارد. فقط ترافیک را از سروری که انتخاب می‌کنید عبور می‌دهد؛ نمی‌تواند پیام‌ها یا فایل‌های شما را بخواند.",
    "Required before protected connections start" to "پیش از شروع اتصال محافظت‌شده لازم است",
    "Allow connection notifications" to "اجازه اعلان‌های اتصال",
    "Android requires notification access for MarbleNG to keep the active tunnel visible and to tell you when a connection changes while the app is in the background." to
        "اندروید برای نمایان نگه‌داشتن تونل فعال و اطلاع‌رسانی تغییرات اتصال در پس‌زمینه، به دسترسی اعلان نیاز دارد.",
    "Keeps tunnel status visible" to "وضعیت تونل را نمایان نگه می‌دارد",
    "Allow background connection" to "اجازه اتصال در پس‌زمینه",
    "Battery optimization can suspend a VPN when the screen turns off. MarbleNG asks to be excluded so the connection remains stable; this does not disable battery saving for other apps." to
        "بهینه‌سازی باتری می‌تواند VPN را با خاموش‌شدن صفحه متوقف کند. MarbleNG درخواست استثنا می‌کند تا اتصال پایدار بماند؛ این کار ذخیره باتری برنامه‌های دیگر را غیرفعال نمی‌کند.",
    "Keeps the route alive when idle" to "مسیر را در حالت بیکار زنده نگه می‌دارد",
    "Only requested when you tap Connect" to "فقط هنگام زدن دکمه اتصال درخواست می‌شود",
    "Continue" to "ادامه",
    "Not now" to "حالا نه",
    "Freedom" to "فریدم",

    // ------------------------------------------------------- MARBLE_SERVERS_V114 / SETTINGS HUB V114
    // The Servers screen: one frosted module per source, compact rows, a clipboard magic button.
    "Server" to "سرور",
    "1 server" to "یک سرور",
    "shown" to "نمایان",
    "End of source" to "پایان منبع",
    "Colony complete" to "کلونی کامل است",
    "END OF MANIFEST" to "پایان فهرست",
    "Field edge" to "لبه میدان",
    "END OF SHEET" to "پایان برگه",
    "ms" to "میلی‌ثانیه",
    "Hold for actions" to "برای اکشن‌ها نگه دارید",
    "Tap to import • hold for options" to "برای افزودن لمس کنید • نگه‌داشتن برای گزینه‌ها",
    "Add servers" to "افزودن سرور",
    "Sort servers" to "مرتب‌سازی سرورها",
    "SIGNATURE SERVERS" to "سرورهای سیگنچر",
    "ORGANIC SERVERS" to "سرورهای ارگانیک",
    "NEBULA SERVERS" to "سرورهای سحابی",
    "BLUEPRINT SERVERS" to "سرورهای نقشه‌ای",
    "ORBITAL MANIFEST" to "فهرست مداری",
    "Not measured" to "اندازه‌گیری نشده",
    "Show Marble Freedom" to "نمایش فریدم ماربل",
    "Hide Marble Freedom" to "پنهان‌کردن فریدم ماربل",

    // The settings hub: one page of titles, each opening its own page, plus the live quick rows.
    "All settings" to "همه تنظیمات",
    "Theme, Home style, Typeface and Language live under Appearance on the Settings hub." to
        "تم، استایل خانه، فونت و زبان زیر «ظاهر» در مرکز تنظیمات قرار دارند.",
    "Hub" to "مرکز",
    "Language" to "زبان",
    "English" to "انگلیسی",
    "Information" to "اطلاعات",
    "Reconnect last server" to "اتصال مجدد به آخرین سرور",
    "Resume the previous route on launch" to "ادامه مسیر قبلی هنگام اجرای برنامه",
    "Auto-refresh sources" to "بروزرسانی خودکار منابع",
    "Keep subscriptions up to date" to "اشتراک‌ها را به‌روز نگه می‌دارد",
    "Smart alerts" to "اعلان‌های هوشمند",
    "Notify only when something needs you" to "فقط وقتی چیزی به شما نیاز دارد اطلاع می‌دهد",
    "Marble Intelligence" to "هوش ماربل",
    "Compatibility checks and verified tuning" to "بررسی سازگاری و تنظیم اثبات‌شده",
    "Expert mode" to "حالت تخصصی",
    "Reveal the low-level tunnel controls" to "نمایش کنترل‌های سطح پایین تونل",
    "Routing, Freedom, tests and servers" to "مسیریابی، فریدم، تست‌ها و سرورها",
    "Theme, Home style, typeface and language" to "پوسته، سبک خانه، قلم و زبان",
    "Notifications, engine, general and information" to "اعلان‌ها، موتور، عمومی و اطلاعات",
    "Network & routing" to "شبکه و مسیریابی",
    "DNS, split tunnel and geo rules" to "DNS، تونل تفکیکی و قوانین جغرافیایی",
    "Tests & ranking" to "تست‌ها و رتبه‌بندی",
    "Ping, speed and smart ranking" to "پینگ، سرعت و رتبه‌بندی هوشمند",
    "General & servers" to "عمومی و سرورها",
    "Alerts, live stats and cooldown" to "اعلان‌ها، آمار زنده و فاصله زمانی",
    "Engine & tunnel" to "موتور و تونل",
    "Xray, transport and adaptive buffers" to "Xray، انتقال و بافرهای تطبیقی",
    "Home layout, sources and app updates" to "چیدمان خانه، منابع و به‌روزرسانی برنامه",
    "Daylight" to "روشنایی روز",
    "Dynamic" to "پویا",
    "Dynamic phone" to "پویای گوشی",
    "Wallpaper colors" to "رنگ‌های کاغذ دیواری",
    "Home style" to "سبک خانه",
    "The Latin face of the whole product" to "قلم لاتین کل محصول",
    "Persian always shapes with Vazirmatn, whichever Latin face you pick." to
        "فارسی همیشه با وزیرمتن نوشته می‌شود، هر قلم لاتینی که انتخاب کنید.",
    "The Persian choice is written in Persian and always rendered with Vazirmatn." to
        "گزینه فارسی به خط فارسی نوشته می‌شود و همیشه با وزیرمتن نمایش داده می‌شود.",
    "Every layer of the Signature studio is customizable under General." to
        "هر لایه از استودیوی سیگنچر در بخش عمومی قابل شخصی‌سازی است.",

    // The Information page: real versions and links that open the browser directly.
    "Versions" to "نسخه‌ها",
    "App version" to "نسخه برنامه",
    "Version code" to "کد نسخه",
    "Xray core" to "هسته Xray",
    "Tunnel core" to "هسته تونل",
    "Build type" to "نوع ساخت",
    "Links" to "پیوندها",
    "Every link opens in your browser" to "هر پیوند در مرورگر شما باز می‌شود",
    "Source code" to "کد منبع",
    "Releases" to "انتشارها",
    "Report an issue" to "گزارش مشکل",
    "Copy details" to "کپی جزئیات",
    "Copy the version details, or keep a continuous diagnostic export in Downloads/marbleng/report." to
        "جزئیات نسخه را کپی کنید، یا خروجی تشخیص پیوسته را در Downloads/marbleng/report نگه دارید.",

    // suffix / unit fragments used by NumberSetting
    " ms" to " میلی‌ثانیه",
    " sec" to " ثانیه",
    " cycles" to " چرخه",

    // ------------------------------------------------------- MARBLE_SERVERS_REDESIGN_V120
    "Clear search" to "پاک کردن جست‌وجو",
    "Clear" to "پاک کردن",
    "All groups" to "همه گروه‌ها",
    "All protocols" to "همه پروتکل‌ها",
    "Advanced filters" to "فیلترهای پیشرفته",
    "Group by country" to "گروه‌بندی بر اساس کشور",
    "Only reachable" to "فقط در دسترس",
    "Max ping" to "بیشترین پینگ",
    "Reset filters" to "بازنشانی فیلترها",
    "Clear filters" to "پاک کردن فیلترها",
    "Refresh all sources" to "به‌روزرسانی همه منابع",
    "All filters…" to "همه فیلترها…",
    "Ping every server" to "پینگ همه سرورها",
    "Ping every server in this group" to "پینگ همه سرورهای این گروه",
    "Measuring servers" to "در حال اندازه‌گیری سرورها",
    "Refreshing sources" to "در حال به‌روزرسانی منابع",
    "Add a server, paste a config or import a subscription to get started." to
        "برای شروع یک سرور اضافه کنید، کانفیگ بچسبانید یا اشتراک وارد کنید.",
    "No server matches the current filters." to "هیچ سروری با فیلترهای فعلی مطابقت ندارد.",
    "This group has no servers yet." to "این گروه هنوز سروری ندارد.",
    "Expires" to "انقضا",
    "Website" to "وب‌سایت",
    "Auto-update on" to "به‌روزرسانی خودکار فعال",
    "Auto-update off" to "به‌روزرسانی خودکار خاموش",
    "Local engine" to "موتور محلی",
    "Local engine • no subscription" to "موتور محلی • بدون اشتراک",
    "Group actions" to "عملیات گروه",
    "Copy subscription URL" to "کپی نشانی اشتراک",
    "Copy all servers" to "کپی همه سرورها",
    "View servers" to "مشاهده سرورها",
    "Show only this group" to "فقط این گروه",
    "Show all groups" to "نمایش همه گروه‌ها",
    "Ping this group" to "پینگ این گروه",
    "Rank this group" to "رتبه‌بندی این گروه",
    "Securing" to "در حال اتصال",
    "Latency" to "تأخیر",
    "Copy link" to "کپی پیوند",
    "Export QR code" to "صادرات کد QR",
    "Move to group" to "انتقال به گروه",
    "Current group" to "گروه فعلی",
    "No other group can hold this server yet." to "گروه دیگری برای این سرور در دسترس نیست.",
    "This config is too long to fit in a QR code." to "این کانفیگ برای کد QR بلندتر از حد مجاز است.",
    "Point another phone at the code to import this server." to
        "گوشی دیگر را روی کد بگیرید تا این سرور وارد شود.",
    "Deleting is confirmed here, never silent." to "حذف همیشه اینجا تأیید می‌شود، هرگز بی‌صدا.",
    "Subscription server • a refresh can replace this edit." to
        "سرور اشتراکی • به‌روزرسانی می‌تواند این ویرایش را جایگزین کند.",
    "Add node" to "افزودن نود",
    "Add chain" to "افزودن زنجیره",
    "Build a server, chain several hops, or import a list." to
        "یک سرور بسازید، چند گام را زنجیره کنید یا فهرستی وارد کنید.",
    "Node" to "نود",
    "Chain" to "زنجیره",
    "Import text" to "متن ورودی",
    "Import file" to "وارد کردن فایل",
    "Manual is enabled" to "Manual فعال است",
    "Enable Manual in Settings → Advanced before saving a built server." to
        "پیش از ذخیره سرور ساخته‌شده، Manual را در تنظیمات → پیشرفته فعال کنید.",
    "Encryption" to "رمزنگاری",
    "UUID" to "UUID",
    "Auth password" to "گذرواژه احراز",
    "SNI" to "SNI",
    "ALPN" to "ALPN",
    "Cipher suites (: separated)" to "مجموعه رمزها (جداشده با :)",
    "Allow insecure certificate" to "پذیرش گواهی ناامن",
    "Ready to save to" to "آماده ذخیره در",
    "Will be added to" to "افزوده می‌شود به",
    " and kept across refreshes." to " و پس از به‌روزرسانی باقی می‌ماند.",
    "Select a group that can hold this server first." to
        "ابتدا گروهی را انتخاب کنید که این سرور را نگه دارد.",
    "Server address is required" to "نشانی سرور لازم است",
    "Port must be between 1 and 65535" to "پورت باید بین ۱ و ۶۵۵۳۵ باشد",
    "UUID is required" to "UUID لازم است",
    "Password is required" to "گذرواژه لازم است",
    "Method is required" to "روش لازم است",
    "Auth password is required" to "گذرواژه احراز لازم است",
    "SSH username is required" to "نام کاربری SSH لازم است",
    "SSH password is required" to "گذرواژه SSH لازم است",
    "Private key is required" to "کلید خصوصی لازم است",
    "Peer public key is required" to "کلید عمومی همتا لازم است",
    "Paste the Xray JSON first" to "ابتدا JSON ایکس‌ری را بچسبانید",
    "VLESS needs TLS/REALITY or a non-none encryption" to
        "VLESS به TLS/REALITY یا رمزنگاری غیر none نیاز دارد"
)

/** Lowercased view of the lexicon so `UPPERCASE` renders of the same keys still match. */
private val FaLexiconLower: Map<String, String> =
    FaLexicon.entries.associate { it.key.lowercase() to it.value }

// Compound runtime strings ("12 nodes", "3 visible • 40 total", "45 sec", …).
private val FaPatterns: List<Pair<Regex, (MatchResult) -> String>> = listOf(
    Regex("""^(\d+) servers$""") to { m -> "${m.groupValues[1]} سرور" },
    // MARBLE_SERVERS_REDESIGN_V120 — the page header count, a folded group and the per-card menu.
    Regex("""^(\d+) groups • (\d+) servers$""") to { m ->
        "${m.groupValues[1]} گروه • ${m.groupValues[2]} سرور"
    },
    Regex("""^(\d+) servers hidden$""") to { m -> "${m.groupValues[1]} سرور پنهان" },
    Regex("""^(\d+) servers • (.+)$""") to { m ->
        "${m.groupValues[1]} سرور • ${m.groupValues[2]}"
    },
    Regex("""^(.+) • (\d+) shown$""") to { m -> "${m.groupValues[1]} • ${m.groupValues[2]} نمایان" },
    Regex("""^Refresh (.+)$""") to { m -> "به‌روزرسانی ${m.groupValues[1]}" },
    Regex("""^More actions for (.+)$""") to { m -> "عملیات بیشتر برای ${m.groupValues[1]}" },
    // MARBLE_SERVERS_V114 — the source module reports its visible slice, the Freedom engine its own
    // count, and the latency readout speaks its measurement to TalkBack.
    Regex("""^(\d+) shown$""") to { m -> "${m.groupValues[1]} نمایان" },
    Regex("""^Freedom \((\d+)\)$""") to { m -> "فریدم (${m.groupValues[1]})" },
    Regex("""^Latency (\d+) milliseconds, (.+)$""") to { m ->
        "تأخیر ${m.groupValues[1]} میلی‌ثانیه، ${m.groupValues[2]}"
    },
    Regex("""^(\d+) local servers$""") to { m -> "${m.groupValues[1]} سرور محلی" },
    Regex("""^(\d+) visible • (\d+) total$""") to { m ->
        "${m.groupValues[1]} نمایان • ${m.groupValues[2]} کل"
    },
    Regex("""^Remove failed ping \((\d+)\)$""") to { m -> "حذف پینگ ناموفق (${m.groupValues[1]})" },
    Regex("""^Remove failed tunnel \((\d+)\)$""") to { m -> "حذف تونل ناموفق (${m.groupValues[1]})" },
    Regex("""^SAVE (\d+)-HOP CHAIN$""") to { m -> "ذخیره زنجیره ${m.groupValues[1]} گامه" },
    Regex("""^(\d+) ms$""") to { m -> "${m.groupValues[1]} میلی‌ثانیه" },
    Regex("""^(\d+) sec$""") to { m -> "${m.groupValues[1]} ثانیه" },
    Regex("""^(\d+)m ago$""") to { m -> "${m.groupValues[1]} دقیقه پیش" },
    Regex("""^(\d+)h ago$""") to { m -> "${m.groupValues[1]} ساعت پیش" },
    Regex("""^(\d+)d ago$""") to { m -> "${m.groupValues[1]} روز پیش" },
    Regex("""^just now$""") to { _ -> "همین حالا" }
)

private fun faPattern(text: String): String? {
    for ((regex, render) in FaPatterns) {
        val match = regex.matchEntire(text) ?: continue
        return render(match)
    }
    return null
}
