package com.marbleng.app.core

import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * MARBLE_SERVERS_QR_EXPORT_V120
 *
 * The QR encoder is verified three ways:
 *
 *  1. **Bit-for-bit against an independent reference implementation.** Each [REFERENCE_*] grid was
 *     produced by a separate, widely used QR encoder for the same payload/ECC pair and is compared
 *     module by module below. A single wrong bit anywhere fails the test.
 *  2. **Structurally.** The finder rings, timing lines and the always-dark anchor module are
 *     asserted directly, so a regression in the function-pattern painter cannot pass by accident.
 *  3. **At its capacity edges.** Version selection must stay minimal, and a payload that does not
 *     fit must raise instead of silently emitting a truncated, undecodable symbol.
 */
class QrCodeTest {

    /**
     * Reference symbol 1 at ECC L.
     * Generated by an independent QR implementation and byte-compared module for module.
     */
    private val REFERENCE_1_TEXT = "hello"
    private val REFERENCE_1_ECC = QrEcc.L
    private val REFERENCE_1_VERSION = 1
    private val REFERENCE_1_MASK = 7
    private val REFERENCE_1_ROWS = listOf(
        "111111100101101111111",
        "100000101101001000001",
        "101110101100101011101",
        "101110100101001011101",
        "101110101000101011101",
        "100000101001101000001",
        "111111101010101111111",
        "000000001111100000000",
        "110100110110001110110",
        "011111011100001000011",
        "001101111010110001101",
        "000101001001000001011",
        "000010110110101010000",
        "000000001111000110101",
        "111111101110010101110",
        "100000100111110110000",
        "101110100101001110001",
        "101110101011000101111",
        "101110100110100010101",
        "100000101110011000000",
        "111111101011100101010"
    )

    /**
     * Reference symbol 2 at ECC M.
     * Generated by an independent QR implementation and byte-compared module for module.
     */
    private val REFERENCE_2_TEXT = "vless://550e8400-e29b-41d4-a716-446655440000@1.2.3.4:443?encryption=none&security=tls&sni=example.com#DE"
    private val REFERENCE_2_ECC = QrEcc.M
    private val REFERENCE_2_VERSION = 6
    private val REFERENCE_2_MASK = 2
    private val REFERENCE_2_ROWS = listOf(
        "11111110011001010001110111100101101111111",
        "10000010001011101000100000110010101000001",
        "10111010101001100000111000101000001011101",
        "10111010100100100010001001101111101011101",
        "10111010100001010011010110100001001011101",
        "10000010110100100010100010110000001000001",
        "11111110101010101010101010101010101111111",
        "00000000100101000001010010011001100000000",
        "10111110010001110100100001011110101111100",
        "00110100011111011111011110100001011111001",
        "00100111011001100100010000010100110110110",
        "00011001010000010010111000010011101111000",
        "00111010101110101110000011000111010000111",
        "01110001110000111000110101101001111010001",
        "01001011000110101110001010111010010001010",
        "11010101000001101010110100110011101110010",
        "00010011100011110100101111110101110101100",
        "10011001010000011111101100001101101111011",
        "11101111100110111100101010011000001100000",
        "10011000010110110111011100001001000010000",
        "01101110011001011000101111101100110101101",
        "00010101010101010011000000000011001111101",
        "00000111001101101000010010010000001011000",
        "10011000001000101011111010011000111101010",
        "10010010100011110111101011011110000001111",
        "11001101101101110001000100100001011111101",
        "11010011101100100000101000011000100100000",
        "11000000010100111010110000011001111101010",
        "11000011111001010111000111010111000100100",
        "10011000011111011100111111101001101011001",
        "10010010011110001010100001110000111111110",
        "10100001101100001001011000010011011010011",
        "10110110000010000100001011100100111111111",
        "00000000111111101001100101001011100010011",
        "11111110011110111010111000111001101011110",
        "10000010101101000000111100010001100010010",
        "10111010100001010010000101101100111111100",
        "10111010111111010001010110000001110101011",
        "10111010101110000000000010011010011110000",
        "10000010000111000001010010011011100111010",
        "11111110110100110010000011010100010110100"
    )

    /**
     * Reference symbol 3 at ECC Q.
     * Generated by an independent QR implementation and byte-compared module for module.
     */
    private val REFERENCE_3_TEXT = "سرور MarbleNG 🇩🇪"
    private val REFERENCE_3_ECC = QrEcc.Q
    private val REFERENCE_3_VERSION = 3
    private val REFERENCE_3_MASK = 6
    private val REFERENCE_3_ROWS = listOf(
        "11111110000100010111001111111",
        "10000010111111010010101000001",
        "10111010001111110000101011101",
        "10111010101000001101101011101",
        "10111010110100100101001011101",
        "10000010010100111110101000001",
        "11111110101010101010101111111",
        "00000000101100110001000000000",
        "01011110100100110010011011010",
        "11000100100110000000110100110",
        "10110011000011100010111010111",
        "11101001110111000111001101101",
        "00000111010000111000100110010",
        "01010101101110000111010001101",
        "00011010010110110101011110111",
        "10111100100000100110101001010",
        "10100011011001001100111101100",
        "10000001001000101111011100011",
        "11100011011100010010010001100",
        "11011000000001100010000111001",
        "11100011000010011101111110010",
        "00000000100111100010100010001",
        "11111110001100011111101010100",
        "10000010110011000100100010100",
        "10111010110100011111111110000",
        "10111010100101001100101110010",
        "10111010011101101001000100111",
        "10000010111110110010110110001",
        "11111110011111100000001110100"
    )

    @Test
    fun encodesReferenceSymbolsBitForBit() {
        listOf(
            Triple(REFERENCE_1_TEXT, REFERENCE_1_ECC, REFERENCE_1_ROWS),
            Triple(REFERENCE_2_TEXT, REFERENCE_2_ECC, REFERENCE_2_ROWS),
            Triple(REFERENCE_3_TEXT, REFERENCE_3_ECC, REFERENCE_3_ROWS)
        ).forEach { (text, ecc, expected) ->
            val symbol = QrCode.encode(text, ecc)
            assertEquals(
                "Wrong symbol size for ${ecc.label} payload",
                expected.size * expected.size,
                symbol.modules.size
            )
            for (row in expected.indices) {
                for (column in expected[row].indices) {
                    val want = expected[row][column] == '1'
                    assertEquals(
                        "Module ($row,$column) differs from the reference symbol",
                        want,
                        symbol.isDark(row, column)
                    )
                }
            }
        }
    }

    @Test
    fun referenceVersionsMatchTheEncoderSelection() {
        assertEquals(REFERENCE_1_VERSION, QrCode.encode(REFERENCE_1_TEXT, REFERENCE_1_ECC).version)
        assertEquals(REFERENCE_2_VERSION, QrCode.encode(REFERENCE_2_TEXT, REFERENCE_2_ECC).version)
        assertEquals(REFERENCE_3_VERSION, QrCode.encode(REFERENCE_3_TEXT, REFERENCE_3_ECC).version)
    }

    @Test
    fun everyReferenceMaskChoiceIsReproducible() {
        // The penalty scoring is deterministic, so the same payload always lands on the same mask.
        assertEquals(REFERENCE_1_MASK, chosenMask(REFERENCE_1_TEXT, REFERENCE_1_ECC, REFERENCE_1_ROWS))
        assertEquals(REFERENCE_2_MASK, chosenMask(REFERENCE_2_TEXT, REFERENCE_2_ECC, REFERENCE_2_ROWS))
        assertEquals(REFERENCE_3_MASK, chosenMask(REFERENCE_3_TEXT, REFERENCE_3_ECC, REFERENCE_3_ROWS))
    }

    @Test
    fun finderRingsTimingAndAnchorAreAlwaysPainted() {
        val symbol = QrCode.encode("vless://probe@203.0.113.7:443?security=reality#probe", QrEcc.M)
        val edge = symbol.size
        assertEquals(17 + 4 * symbol.version, edge)

        listOf(0 to 0, 0 to edge - 7, edge - 7 to 0).forEach { (top, left) ->
            for (row in 0..6) {
                for (column in 0..6) {
                    val ring = maxOf(kotlin.math.abs(row - 3), kotlin.math.abs(column - 3))
                    assertEquals(
                        "Finder ring module ($row,$column)",
                        ring != 2,
                        symbol.isDark(top + row, left + column)
                    )
                }
            }
        }

        // The timing lines only run *between* the finders: where a finder sits, its own pattern
        // is on the row/column, so those modules are the finder's business, not the timing's.
        for (position in 8 until edge - 8) {
            val dark = position % 2 == 0
            assertEquals("Horizontal timing at column $position", dark, symbol.isDark(6, position))
            assertEquals("Vertical timing at row $position", dark, symbol.isDark(position, 6))
        }

        assertTrue("Anchor module must stay dark", symbol.isDark(edge - 8, 8))
    }

    @Test
    fun versionSelectionIsMinimalForEveryErrorLevel() {
        assertEquals(1, QrCode.versionFor(1, QrEcc.L))
        assertEquals(1, QrCode.versionFor(17, QrEcc.L))
        assertEquals(2, QrCode.versionFor(18, QrEcc.L))
        // Version 9 is the last one whose byte-mode character count fits in 8 bits, and 230 bytes
        // is its published ceiling; the next byte needs version 10's 16-bit count.
        assertEquals(9, QrCode.versionFor(230, QrEcc.L))
        assertEquals(10, QrCode.versionFor(231, QrEcc.L))
        assertEquals(1, QrCode.versionFor(7, QrEcc.H))
        assertEquals(2, QrCode.versionFor(8, QrEcc.H))
    }

    @Test
    fun payloadTooLargeForTheSymbolIsRejectedNotTruncated() {
        val oversized = "v".repeat(4_000)
        val error = assertThrows(QrCapacityException::class.java) {
            QrCode.encode(oversized, QrEcc.H)
        }
        assertTrue(error.message.orEmpty().contains("does not fit"))
    }

    @Test
    fun utf8PayloadsMeasureInBytesNotCharacters() {
        // Persian text and the flag surrogate pair are multi-byte, so the symbol grows accordingly.
        val ascii = "a".repeat(20)
        val persian = "س".repeat(20)
        assertTrue(
            QrCode.versionFor(persian.toByteArray(Charsets.UTF_8).size, QrEcc.M)!! >
                QrCode.versionFor(ascii.toByteArray(Charsets.UTF_8).size, QrEcc.M)!!
        )
    }

    @Test
    fun encodingIsStableAcrossRepeatedCalls() {
        val payload = "trojan://secret@example.org:443?sni=example.org#stable"
        val first = QrCode.encode(payload, QrEcc.Q).modules.toList()
        val second = QrCode.encode(payload, QrEcc.Q).modules.toList()
        assertEquals(first, second)
    }

    /**
     * Recover the mask a symbol was built with by reading its two format-information strips.
     */
    private fun chosenMask(text: String, ecc: QrEcc, rows: List<String>): Int {
        val symbol = QrCode.encode(text, ecc)
        val edge = symbol.size
        var bits = 0
        for (bit in 0..14) {
            val row = when {
                bit < 6 -> bit
                bit < 8 -> bit + 1
                else -> edge - 15 + bit
            }
            if (symbol.isDark(row, 8)) bits = bits or (1 shl bit)
        }
        val decoded = bits xor 0b101_0100_0001_0010
        // The five data bits sit at the top of the 15-bit codeword: two ECC bits then the mask.
        assertEquals(ecc.bits, (decoded ushr 13) and 0b11)
        // Sanity: the grid the test compares against is the very grid the mask was read from.
        assertEquals(rows.size, edge)
        return (decoded ushr 10) and 0b111
    }
}
