package com.marbleng.app.core

// MARBLE_BUG_FINDER_ULTIMATE_V15
// MARBLE_RUNTIME_STARTUP_RESCUE_V21
// MARBLE_EXIT_RECENCY_V23
// MARBLE_MEMORY_EXIT_CLASSIFICATION_V26

import android.app.ActivityManager
import android.app.ApplicationExitInfo
import android.content.Context
import android.os.Build
import android.os.Debug
import android.os.Process
import com.marbleng.app.model.AppSettings
import com.marbleng.app.model.ConnectionMode
import com.marbleng.app.model.ConnectionRecord
import com.marbleng.app.model.ProxyProfile
import java.io.File
import java.io.RandomAccessFile
import java.net.InetSocketAddress
import java.time.Instant
import java.util.ArrayDeque

enum class BugSeverity { PASS, INFO, WARN, FAIL }

data class BugCheck(
    val title: String,
    val severity: BugSeverity,
    val detail: String,
    val action: String = ""
)

data class BugSection(
    val title: String,
    val body: String
)

data class BugReport(
    val generatedAt: Long,
    val state: String,
    val checks: List<BugCheck>,
    val evidence: List<String>,
    val sections: List<BugSection> = emptyList()
) {
    val failures get() = checks.count { it.severity == BugSeverity.FAIL }
    val warnings get() = checks.count { it.severity == BugSeverity.WARN }
    val passed get() = checks.count { it.severity == BugSeverity.PASS }

    val headline: String
        get() = when {
            failures > 0 -> "$failures current critical issue${if (failures == 1) "" else "s"} found"
            warnings > 0 -> "$warnings diagnostic warning${if (warnings == 1) "" else "s"} found"
            else -> "Runtime looks healthy • full evidence captured"
        }

    fun asText(): String = buildString {
        appendLine("=== MarbleNG BUG FINDER ULTIMATE v15 ===")
        appendLine("generated=${Instant.ofEpochMilli(generatedAt)}")
        appendLine("state=$state")
        appendLine("result=$headline")
        appendLine("pass=$passed warn=$warnings fail=$failures")
        appendLine("mode=PASSIVE OBSERVATION • no external connectivity probes generated by Bug Finder")
        appendLine()

        appendLine("=== HEALTH CHECKS ===")
        checks.forEach {
            appendLine("[${it.severity}] ${it.title}")
            appendLine(it.detail)
            if (it.action.isNotBlank()) appendLine("Action: ${it.action}")
            appendLine()
        }

        sections.forEach { section ->
            appendLine("=== ${section.title} ===")
            appendLine(section.body.ifBlank { "No evidence" })
            appendLine()
        }

        if (evidence.isNotEmpty()) {
            appendLine("=== PRIORITY ERROR / CRASH / BUG EVIDENCE ===")
            evidence.forEach(::appendLine)
        }

        appendLine()
        appendLine("=== PRIVACY NOTE ===")
        appendLine("Raw proxy/share configs, UUIDs, passwords, tokens, private keys and auth material are redacted.")
    }
}

private data class ExitEvidence(
    val text: String,
    val crashLike: Int,
    val lowMemory: Int
)

class BugFinder(private val context: Context, private val xray: XrayManager) {
    private val diag = RuntimeDiagnostics(context)

    fun scan(
        appState: String,
        stateDetail: String,
        activeProfileId: String,
        settings: AppSettings,
        profiles: List<ProxyProfile>,
        history: List<ConnectionRecord>,
        networkLabel: String
    ): BugReport {
        RuntimeDiagnostics.flush(2_000L)

        val now = System.currentTimeMillis()
        val checks = mutableListOf<BugCheck>()
        val sections = mutableListOf<BugSection>()
        val connected = appState == "CONNECTED"
        val fullTun = settings.connectionMode == ConnectionMode.FULL_TUN
        val port = if (fullTun) settings.socksPort else settings.localProxyPort

        val runtime = tail(File(context.filesDir, "logs/runtime-debug.log"), 700_000)
        val runtime1 = tail(File(context.filesDir, "logs/runtime-debug.log.1"), 350_000)
        val runtime2 = tail(File(context.filesDir, "logs/runtime-debug.log.2"), 250_000)
        val hevLog = tail(File(context.filesDir, "logs/hev-native.log"), 250_000)
        val xrayLog = tail(xray.logFile, 300_000)
        val crashPending = tail(File(context.filesDir, "logs/fatal-crash-pending.txt"), 120_000)

        val allRuntime = listOf(runtime2, runtime1, runtime)
            .filterNot { it.startsWith("No log file yet:") }
            .joinToString("\n")

        val xbin = File(context.applicationInfo.nativeLibraryDir, "libxray.so")
        checks += if (xbin.isFile && xbin.length() > 0L) {
            BugCheck("Xray native core", BugSeverity.PASS, "${xbin.length()} bytes present")
        } else {
            BugCheck("Xray native core", BugSeverity.FAIL, "libxray.so is missing", "Rebuild the core bundle")
        }

        val jni = File(context.applicationInfo.nativeLibraryDir, "libmarbleng.so")
        checks += if (jni.isFile && jni.length() > 0L) {
            BugCheck("HEV JNI bridge", BugSeverity.PASS, "${jni.length()} bytes present")
        } else {
            BugCheck("HEV JNI bridge", BugSeverity.FAIL, "libmarbleng.so is missing", "Rebuild native HEV")
        }

        checks += when {
            profiles.isEmpty() -> BugCheck("Config library", BugSeverity.FAIL, "No profiles installed")
            connected && activeProfileId.isBlank() ->
                BugCheck("Active profile", BugSeverity.FAIL, "CONNECTED but activeProfileId is empty", "Safe runtime reset")
            connected && profiles.none { it.id == activeProfileId } ->
                BugCheck("Active profile", BugSeverity.FAIL, "Connected profile no longer exists", "Reconnect a valid node")
            else -> BugCheck("Config library", BugSeverity.PASS, "${profiles.size} profiles • ${stateDetail.ifBlank { "idle" }}")
        }

        checks += BugCheck("Android underlay", BugSeverity.INFO, networkLabel.ifBlank { "Unknown network" })

        val alive = xray.isAlive
        val xrayPid = xray.processPid
        checks += when {
            connected && !alive -> BugCheck("Xray process", BugSeverity.FAIL, "UI says CONNECTED but Xray is dead", "Safe runtime reset")
            alive -> BugCheck("Xray process", BugSeverity.PASS, "alive=true • pid=${xrayPid.takeIf { it > 0 } ?: "unknown"}")
            else -> BugCheck("Xray process", BugSeverity.INFO, "Xray stopped while app is $appState")
        }

        val latestStartCommand = allRuntime.lastIndexOf("VPN | command | action=com.marbleng.START")
        val latestConnectRequest = allRuntime.lastIndexOf("VPN | connect-request")
        val latestStartupTimeout = allRuntime.lastIndexOf("VPN | startup-timeout")
        val latestSocksReady = allRuntime.lastIndexOf("XRAY | socks-ready")
        val latestHevReady = allRuntime.lastIndexOf("HEV | ready")
        val latestReady = maxOf(latestSocksReady, latestHevReady)

        checks += when {
            appState == "CONNECTING" &&
                !alive &&
                latestStartCommand > latestStartupTimeout &&
                latestStartupTimeout > latestConnectRequest &&
                latestStartupTimeout > latestReady -> BugCheck(
                "Startup command progression",
                BugSeverity.FAIL,
                "Queued START stalled before connect-request; previous cleanup/core start did not release promptly",
                "Safe runtime reset, then retry"
            )
            appState in setOf("CONNECTING", "BLOCKED") &&
                latestStartupTimeout > latestConnectRequest &&
                latestStartupTimeout > latestReady -> BugCheck(
                "Startup watchdog",
                BugSeverity.FAIL,
                "Latest connection attempt hit the startup timeout before Xray/HEV became ready",
                "Inspect XRAY start-result/start phase and routing assets"
            )
            appState == "BLOCKED" -> BugCheck(
                "Startup / blocked state",
                BugSeverity.FAIL,
                stateDetail.ifBlank { "Runtime is BLOCKED" },
                "Inspect the connection timeline before retrying"
            )
            appState == "CONNECTING" && !alive -> BugCheck(
                "Startup progression",
                BugSeverity.WARN,
                "CONNECTING while Xray is not alive yet; no newer ready event is retained",
                "Re-run Bug Finder if this state persists"
            )
            else -> BugCheck(
                "Startup progression",
                BugSeverity.PASS,
                "No unresolved startup timeout or stalled START command in the current runtime state"
            )
        }

        val listener = alive && listenerBoundWithoutTraffic(port)
        checks += when {
            listener -> BugCheck("Local SOCKS listener", BugSeverity.PASS, "127.0.0.1:$port is bound • checked without opening a SOCKS connection")
            alive -> BugCheck("Local SOCKS listener", BugSeverity.FAIL, "Xray is alive but port $port is not bound", "Restart route")
            else -> BugCheck("Local SOCKS listener", BugSeverity.INFO, "Skipped because Xray is stopped")
        }

        checks += BugCheck(
            "Bug Finder traffic policy",
            BugSeverity.PASS,
            "Passive diagnostics only • no HTTP/DNS/tunnel test is generated by this scan"
        )

        if (fullTun && connected) {
            val connect = allRuntime.lastIndexOf("VPN | connect-request")
            val tun = allRuntime.lastIndexOf("TUN | established")
            val hevEnter = allRuntime.lastIndexOf("HEV | run-enter")
            val hevExit = allRuntime.lastIndexOf("HEV | run-exit")
            val blocked = allRuntime.lastIndexOf("VPN | blocked")

            checks += when {
                connect >= 0 && blocked > connect && blocked > tun ->
                    BugCheck("VPN lifecycle", BugSeverity.FAIL, "Latest connection attempt entered BLOCKED", "Inspect connection timeline")
                tun < connect ->
                    BugCheck("Android TUN lifecycle", BugSeverity.FAIL, "No TUN established after latest connect request", "Inspect VPN lifecycle evidence")
                hevEnter < tun ->
                    BugCheck("HEV lifecycle", BugSeverity.FAIL, "TUN established but no HEV run-enter followed", "Inspect native HEV evidence")
                hevExit > hevEnter ->
                    BugCheck("HEV lifecycle", BugSeverity.FAIL, "Latest HEV run exited while UI is CONNECTED", "Reconnect and inspect HEV exit")
                else -> BugCheck("TUN + HEV lifecycle", BugSeverity.PASS, "Latest lifecycle is consistent with CONNECTED")
            }

            checks += BugCheck(
                "Native statistics safety",
                BugSeverity.PASS,
                "Bug Finder does not call HevTunnel.stats; it consumes service/native logs instead so diagnostics cannot race HEV startup"
            )
        } else if (connected) {
            checks += BugCheck("Forwarding mode", BugSeverity.INFO, "Local proxy mode • TUN/HEV lifecycle checks not required")
        }

        val assets = xray.routingAssetStatus()
        checks += when {
            settings.routeBlockAds && !assets.geoSiteReady ->
                BugCheck("GeoSite asset", BugSeverity.FAIL, "Ad/routing policy needs geosite.dat but it is missing", "Prepare routing assets")
            settings.routingMode.name.contains("GEO") && !assets.geoIpReady ->
                BugCheck("GeoIP asset", BugSeverity.FAIL, "Geo routing selected but geoip.dat is missing", "Prepare routing assets")
            else -> BugCheck("Routing assets", BugSeverity.PASS, "geoip=${assets.geoIpReady} (${assets.geoIpBytes}) • geosite=${assets.geoSiteReady} (${assets.geoSiteBytes})")
        }

        val diagnosticStatus = RuntimeDiagnostics.status()
        checks += when {
            diagnosticStatus.dropped > 0 -> BugCheck(
                "Diagnostics backpressure",
                BugSeverity.WARN,
                "${diagnosticStatus.dropped} diagnostic entries were dropped instead of slowing the app",
                "Keep Debug Mode only while investigating if storage is extremely slow"
            )
            !diagnosticStatus.writerHealthy -> BugCheck(
                "Diagnostics writer",
                BugSeverity.WARN,
                diagnosticStatus.writerError.ifBlank { "Writer reported an unknown failure" },
                "Check storage availability"
            )
            else -> BugCheck(
                "Diagnostics fast path",
                BugSeverity.PASS,
                "queue=${diagnosticStatus.queued}/4096 • dropped=${diagnosticStatus.dropped} • ring=${diagnosticStatus.ringEvents}"
            )
        }

        val exits = historicalExits(now)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            checks += when {
                exits.crashLike > 0 -> BugCheck(
                    "Historical process exits",
                    BugSeverity.WARN,
                    "${exits.crashLike} crash/ANR/native-crash exit record(s) found in Android history",
                    "Review the PROCESS EXIT HISTORY section"
                )
                exits.lowMemory > 0 -> BugCheck(
                    "Historical process exits",
                    BugSeverity.INFO,
                    "${exits.lowMemory} historical Android LOW_MEMORY exit record(s) found • " +
                        "system pressure evidence, not a Java/native crash; v26 trim hooks are armed",
                    "Full process-exit evidence is preserved below"
                )
                else -> BugCheck("Historical process exits", BugSeverity.PASS, "No recent crash/ANR record returned by Android")
            }
        } else {
            checks += BugCheck(
                "Historical process exits",
                BugSeverity.INFO,
                "ApplicationExitInfo requires Android 11+; fatal tombstones and runtime logs remain available"
            )
        }

        val active = profiles.firstOrNull { it.id == activeProfileId }
        sections += BugSection("SYSTEM / BUILD", systemSection(settings, diagnosticStatus))
        sections += BugSection(
            "CURRENT CONNECTION",
            buildString {
                appendLine("appState=$appState")
                appendLine("stateDetail=${sanitize(stateDetail)}")
                appendLine("mode=${settings.connectionMode}")
                appendLine("network=${sanitize(networkLabel)}")
                appendLine("activeProfileId=${activeProfileId.take(16)}")
                if (active != null) {
                    appendLine("profileName=${sanitize(active.name)}")
                    appendLine("scheme=${active.scheme}")
                    appendLine("transport=${active.transport}")
                    appendLine("security=${active.security}")
                    appendLine("endpoint=${sanitize(active.host)}:${active.port}")
                    appendLine("configFingerprint=${diag.sha256(active.configJson)}")
                }
                appendLine("xrayAlive=${xray.isAlive}")
                appendLine("xrayPid=${xray.processPid}")
                appendLine("xrayStartPhase=${sanitize(xray.lastStartPhase)}")
                appendLine("xrayLastStartError=${sanitize(xray.lastStartError)}")
                appendLine("listenerBound=$listener")
                appendLine("socksPort=$port")
                appendLine("fragment=${settings.fragmentEnabled}")
                appendLine("mux=${settings.muxEnabled}")
                appendLine("dnsStrategy=${settings.dnsQueryStrategy}")
                appendLine("routing=${settings.routingMode}")
                appendLine("debugMode=${settings.debugModeEnabled}")
            }
        )

        sections += BugSection("APP PROCESS + MEMORY", processSection())
        sections += BugSection("ALL APP THREADS", threadSection())
        sections += BugSection(
            "CONNECTION HISTORY",
            if (history.isEmpty()) {
                "No persisted connection history"
            } else {
                history.takeLast(200).joinToString("\n") {
                    "${Instant.ofEpochMilli(it.at)} | profile=${it.profileId.take(16)} | " +
                        "name=${sanitize(it.name)} | reason=${sanitize(it.reason)}"
                }
            }
        )
        sections += BugSection("CONNECTION / ENGINE EVENT TIMELINE", connectionTimeline(allRuntime))
        sections += BugSection("ANDROID PROCESS EXIT HISTORY", exits.text)
        sections += BugSection(
            "DIAGNOSTICS ENGINE",
            buildString {
                appendLine("debugEnabled=${diagnosticStatus.debugEnabled}")
                appendLine("publicPath=${diagnosticStatus.publicPath}")
                appendLine("queue=${diagnosticStatus.queued}/4096")
                appendLine("dropped=${diagnosticStatus.dropped}")
                appendLine("ringEvents=${diagnosticStatus.ringEvents}")
                appendLine("writerHealthy=${diagnosticStatus.writerHealthy}")
                appendLine("writerError=${sanitize(diagnosticStatus.writerError)}")
            }
        )

        val problemEvidence = (
            problems(allRuntime).takeLast(220) +
                problems(hevLog).takeLast(120) +
                problems(xrayLog).takeLast(160) +
                problems(crashPending).takeLast(40)
            ).distinct().takeLast(400)

        sections += BugSection(
            "ERROR / CRASH / BUG INDEX",
            if (problemEvidence.isEmpty()) "No error-like evidence in retained logs"
            else problemEvidence.joinToString("\n")
        )
        sections += BugSection("IN-MEMORY EVENT RING", RuntimeDiagnostics.recentEvents(700).joinToString("\n"))
        sections += BugSection("RUNTIME LOG RETAINED TAIL", sanitize(allRuntime))
        sections += BugSection("HEV NATIVE RETAINED TAIL", sanitize(hevLog))
        sections += BugSection("XRAY RETAINED TAIL", sanitize(xrayLog))
        if (crashPending.isNotBlank() && !crashPending.startsWith("No log file yet:")) {
            sections += BugSection("PENDING FATAL CRASH TOMBSTONE", sanitize(crashPending))
        }

        return BugReport(
            generatedAt = now,
            state = "$appState • ${stateDetail.ifBlank { "no active route" }}",
            checks = checks,
            evidence = problemEvidence.takeLast(80),
            sections = sections
        )
    }

    private fun systemSection(settings: AppSettings, status: DiagnosticEngineStatus): String {
        val pi = runCatching { context.packageManager.getPackageInfo(context.packageName, 0) }.getOrNull()
        val versionCode = if (pi == null) -1L
        else if (Build.VERSION.SDK_INT >= 28) pi.longVersionCode
        else {
            @Suppress("DEPRECATION")
            pi.versionCode.toLong()
        }

        return buildString {
            appendLine(diag.systemSnapshot())
            appendLine("package=${context.packageName}")
            appendLine("versionName=${pi?.versionName.orEmpty()}")
            appendLine("versionCode=$versionCode")
            appendLine("filesDir=${context.filesDir.absolutePath}")
            appendLine("debugOutput=${status.publicPath}")
            appendLine("debugEnabled=${settings.debugModeEnabled}")
            appendLine("generated=${Instant.now()}")
        }
    }

    private fun processSection(): String {
        val am = runCatching { context.getSystemService(ActivityManager::class.java) }.getOrNull()
        val rt = Runtime.getRuntime()
        val own = runCatching {
            am?.runningAppProcesses.orEmpty().filter { it.uid == Process.myUid() }
        }.getOrDefault(emptyList())
        val pss = runCatching {
            am?.getProcessMemoryInfo(intArrayOf(Process.myPid()))?.firstOrNull()?.totalPss
        }.getOrNull() ?: -1

        return buildString {
            appendLine("pid=${Process.myPid()} uid=${Process.myUid()}")
            appendLine("elapsedCpuMs=${Process.getElapsedCpuTime()}")
            appendLine("javaHeapUsed=${rt.totalMemory() - rt.freeMemory()}")
            appendLine("javaHeapCommitted=${rt.totalMemory()}")
            appendLine("javaHeapMax=${rt.maxMemory()}")
            appendLine("nativeHeapAllocated=${Debug.getNativeHeapAllocatedSize()}")
            appendLine("pssKb=$pss")
            appendLine("visibleOwnProcesses=${own.size}")
            own.forEach {
                appendLine(
                    "pid=${it.pid} process=${sanitize(it.processName)} importance=${it.importance} " +
                        "reasonCode=${it.importanceReasonCode}"
                )
            }
            if (own.isEmpty()) appendLine("Android did not expose a running-process row; own PID above remains authoritative.")
            appendLine("Note: modern Android does not permit reliable enumeration of every unrelated device process.")
        }
    }

    private fun threadSection(): String {
        val threads = Thread.getAllStackTraces().entries
            .sortedWith(compareBy({ it.key.name }, { it.key.id }))
            .take(160)

        return buildString {
            appendLine("captured=${threads.size}")
            threads.forEach { (thread, stack) ->
                appendLine()
                appendLine(
                    "THREAD id=${thread.id} name=${sanitize(thread.name)} state=${thread.state} " +
                        "daemon=${thread.isDaemon} priority=${thread.priority}"
                )
                stack.take(12).forEach { frame -> appendLine("  at ${sanitize(frame.toString())}") }
            }
        }
    }

    private fun historicalExits(now: Long): ExitEvidence {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
            return ExitEvidence("Unavailable on Android ${Build.VERSION.SDK_INT}; requires API 30+.", 0, 0)
        }

        val am = context.getSystemService(ActivityManager::class.java)
        val exits = runCatching {
            am.getHistoricalProcessExitReasons(context.packageName, 0, 32)
        }.getOrDefault(emptyList())

        var crashLike = 0
        var lowMemory = 0
        val warningCutoff = now - 24L * 60L * 60L * 1000L
        val text = buildString {
            appendLine("records=${exits.size}")
            appendLine("warningWindowHours=24")
            exits.forEachIndexed { index, exit ->
                val reason = exitReason(exit.reason)
                if (
                    exit.timestamp >= warningCutoff &&
                    (
                        exit.reason == ApplicationExitInfo.REASON_CRASH ||
                        exit.reason == ApplicationExitInfo.REASON_CRASH_NATIVE ||
                        exit.reason == ApplicationExitInfo.REASON_ANR
                    )
                ) crashLike++
                if (
                    exit.timestamp >= warningCutoff &&
                    exit.reason == ApplicationExitInfo.REASON_LOW_MEMORY
                ) lowMemory++

                appendLine()
                appendLine("#${index + 1} ${Instant.ofEpochMilli(exit.timestamp)}")
                appendLine("process=${sanitize(exit.processName.orEmpty())}")
                appendLine("reason=$reason (${exit.reason})")
                appendLine("status=${exit.status}")
                appendLine("importance=${exit.importance}")
                appendLine("pssKb=${exit.pss} rssKb=${exit.rss}")
                appendLine("description=${sanitize(exit.description.orEmpty())}")

                if (index < 8) {
                    val trace = runCatching {
                        exit.traceInputStream?.bufferedReader()?.use { reader -> reader.readText().take(80_000) }
                    }.getOrNull()
                    if (!trace.isNullOrBlank()) {
                        appendLine("--- exit trace ---")
                        appendLine(sanitize(trace))
                    }
                }
            }
        }
        return ExitEvidence(text, crashLike, lowMemory)
    }

    private fun exitReason(reason: Int): String = when (reason) {
        ApplicationExitInfo.REASON_UNKNOWN -> "UNKNOWN"
        ApplicationExitInfo.REASON_EXIT_SELF -> "EXIT_SELF"
        ApplicationExitInfo.REASON_SIGNALED -> "SIGNALED"
        ApplicationExitInfo.REASON_LOW_MEMORY -> "LOW_MEMORY"
        ApplicationExitInfo.REASON_CRASH -> "JAVA_CRASH"
        ApplicationExitInfo.REASON_CRASH_NATIVE -> "NATIVE_CRASH"
        ApplicationExitInfo.REASON_ANR -> "ANR"
        ApplicationExitInfo.REASON_INITIALIZATION_FAILURE -> "INITIALIZATION_FAILURE"
        ApplicationExitInfo.REASON_PERMISSION_CHANGE -> "PERMISSION_CHANGE"
        ApplicationExitInfo.REASON_EXCESSIVE_RESOURCE_USAGE -> "EXCESSIVE_RESOURCE_USAGE"
        ApplicationExitInfo.REASON_USER_REQUESTED -> "USER_REQUESTED"
        ApplicationExitInfo.REASON_USER_STOPPED -> "USER_STOPPED"
        ApplicationExitInfo.REASON_DEPENDENCY_DIED -> "DEPENDENCY_DIED"
        ApplicationExitInfo.REASON_OTHER -> "OTHER"
        else -> "REASON_$reason"
    }

    private fun connectionTimeline(text: String): String {
        if (text.isBlank()) return "No retained runtime timeline"
        val tags = listOf(
            "APP |", "VPN |", "TUN |", "HEV |", "XRAY |", "EGRESS |", "DNS |",
            "IDENTITY |", "TURBO |", "AUTOPILOT |", "PRIVACY |", "NETWORK |"
        )
        val lines = text.lineSequence()
            .filter { line -> tags.any(line::contains) }
            .map(::sanitize)
            .takeLastCompat(1_000)
        return if (lines.isEmpty()) "No matching retained events" else lines.joinToString("\n")
    }

    private fun problems(text: String): List<String> {
        if (text.isBlank()) return emptyList()
        val keywords = listOf(
            "error", "fail", "fatal", "crash", "anr", "blocked", "exception", "timeout",
            "refused", "denied", "killed", "run-exit", "stall", "dead", "abort", "panic",
            "signal", "oom", "low_memory"
        )

        return text.lineSequence()
            .filter { line ->
                val cleanHevExit =
                    line.contains("HEV | run-exit", true) &&
                        line.contains("code=0", true) &&
                        line.contains("runningFlag=false", true) &&
                        line.contains("xrayAlive=false", true)
                val benignNoise =
                    line.contains("proxy/socks: failed to read request > EOF", true) ||
                        (line.contains("HTTPUpgrade transport", true) && line.contains("deprecated", true))
                !cleanHevExit && !benignNoise && keywords.any { line.contains(it, true) }
            }
            .map(::sanitize)
            .takeLastCompat(500)
    }

    private fun listenerBoundWithoutTraffic(port: Int): Boolean = runCatching {
        java.net.ServerSocket().use { socket ->
            socket.reuseAddress = true
            socket.bind(InetSocketAddress("127.0.0.1", port))
        }
        false
    }.getOrElse { true }

    private fun tail(file: File, maxBytes: Int): String {
        if (!file.isFile) return "No log file yet: ${file.name}"
        return runCatching {
            RandomAccessFile(file, "r").use { raf ->
                val read = raf.length().coerceAtMost(maxBytes.toLong()).toInt()
                raf.seek((raf.length() - read).coerceAtLeast(0L))
                val bytes = ByteArray(read)
                raf.readFully(bytes)
                String(bytes, Charsets.UTF_8)
            }
        }.getOrElse { "Could not read ${file.name}: ${it::class.java.simpleName}: ${it.message}" }
    }

    private fun sanitize(value: String): String = RuntimeDiagnostics.redact(value).take(250_000)

    private fun <T> Sequence<T>.takeLastCompat(limit: Int): List<T> {
        val deque = ArrayDeque<T>()
        forEach { value ->
            deque.addLast(value)
            while (deque.size > limit) deque.removeFirst()
        }
        return deque.toList()
    }
}
